### ISSUE TITLE
Difficult to see white star on a white background

### ISSUE THREAD

**Issue by OmlineEditor** [TheLastProject/Catima#619]
I ask you to make a black border of several pixels so that the white star can be better seen on a white background.

![1](https://user-images.githubusercontent.com/13348933/143725200-48629f3d-26bb-4240-98c3-d9896f30dcd6.jpg)

**Comment by TheLastProject** [comment]
This should be fixed in #675.

**Comment by OmlineEditor** [comment]
the problem is not solved. please open the ticket again

![1](https://user-images.githubusercontent.com/13348933/147888365-239ffd1b-5ceb-41ba-8cfd-8f26c912357c.jpg)

**Comment by TheLastProject** [comment]
Can you share that image you're using? The problem seems to only exist for that image because it is mostly dark with a bit of white so the dark version of the star gets applied to it.

**Comment by OmlineEditor** [comment]
for a white star, you need to make a black border. for a black star, white edging is needed.

![scrt](https://user-images.githubusercontent.com/13348933/147888747-f68c6ca7-58b7-4827-8050-3f99bc4bf623.jpg)

Test image:

![test](https://user-images.githubusercontent.com/13348933/147888733-fdef32b2-eaa6-46d3-812b-8b650cf9d983.png)
![5](https://user-images.githubusercontent.com/13348933/147888737-361df6b7-56b3-43bb-892d-8fa934f6e241.png)

**Comment by TheLastProject** [comment]
I guess something like this then:
![image](https://user-images.githubusercontent.com/1885159/147889685-babbbda4-d291-4646-9a44-c7752e1482a1.png)

It looks slightly uglier to me, but Android's layout XML is stupid and buggy and annoying so unless someone else shows up who wants to spend hours dealing with the pain and misery that is Android's layout XML this is the best it's going to get because everything else I tried over the past hour looked worse.

Fixed in 58ebb7c7bf07ad69a95d9a90b344df1e84914126.

**Comment by Altonss** [comment]
That looks to solve the issue, so it's great! Another solution to improve the design would maybe be to drop the transparency of the star...

**Comment by TheLastProject** [comment]
> That looks to solve the issue, so it's great! Another solution to improve the design would maybe be to drop the transparency of the star...

Yeah I tried that but it looks awful:
![image](https://user-images.githubusercontent.com/1885159/147890133-a1a9795c-e341-4d46-89df-f60147190e8a.png)

**Comment by OmlineEditor** [comment]
a gray star is more beautiful than a black and white one. thank you for solving the problem
